-- Nominee Service Database Schema (SQLite)

-- One owner-to-nominee grant. The unique key is the PAIR, not the owner:
-- an owner may nominate any number of people, but each of them only once.
CREATE TABLE IF NOT EXISTS NOMINATION (
  NOMINATION_ID         CHAR(36) NOT NULL,
  OWNER_ID              VARCHAR(255) NOT NULL,
  NOMINEE_ID            VARCHAR(255) NOT NULL,
  NOMINEE_EMAIL         VARCHAR(255) NOT NULL,
  NOMINEE_NIC           VARCHAR(64) DEFAULT NULL,
  CURRENT_STATUS        VARCHAR(32) NOT NULL,
  NOMINATED_TIME        BIGINT NOT NULL,
  ACCEPTED_TIME         BIGINT DEFAULT NULL,
  ACTIVATED_BY          VARCHAR(255) DEFAULT NULL,
  ACTIVATED_TIME        BIGINT DEFAULT NULL,
  ACTIVATION_TICKET     VARCHAR(255) DEFAULT NULL,
  DEACTIVATED_BY        VARCHAR(255) DEFAULT NULL,
  DEACTIVATED_TIME      BIGINT DEFAULT NULL,
  DEACTIVATION_REASON   TEXT DEFAULT NULL,
  ORG_ID                VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (NOMINATION_ID, ORG_ID),
  UNIQUE (OWNER_ID, NOMINEE_ID, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_nomination_owner_id       ON NOMINATION (OWNER_ID);
CREATE INDEX IF NOT EXISTS idx_nomination_nominee_id     ON NOMINATION (NOMINEE_ID);
CREATE INDEX IF NOT EXISTS idx_nomination_status         ON NOMINATION (CURRENT_STATUS);
CREATE INDEX IF NOT EXISTS idx_nomination_nominee_status ON NOMINATION (NOMINEE_ID, CURRENT_STATUS, ORG_ID);
CREATE INDEX IF NOT EXISTS idx_nomination_org_id         ON NOMINATION (ORG_ID);

-- What the owner granted this nominee. One row per permission.
CREATE TABLE IF NOT EXISTS NOMINATION_PERMISSION (
  NOMINATION_ID     CHAR(36) NOT NULL,
  PERMISSION        VARCHAR(32) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (NOMINATION_ID, PERMISSION, ORG_ID),
  CONSTRAINT FK_NOMINATION_PERMISSION
    FOREIGN KEY (NOMINATION_ID, ORG_ID)
    REFERENCES NOMINATION (NOMINATION_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_nomination_permission ON NOMINATION_PERMISSION (PERMISSION);

-- Lifecycle of a nomination: created, accepted, activated, deactivated, removed.
-- Low volume and kept permanently. Hash-chained: HASH covers this row's own
-- fields plus PREVIOUS_HASH, so altering or removing a row invalidates every
-- row after it. CHAIN_SEQUENCE is global across this table and NOMINEE_SESSION,
-- which together form one chain.
CREATE TABLE IF NOT EXISTS NOMINATION_EVENT (
  EVENT_ID          CHAR(36) NOT NULL,
  NOMINATION_ID     CHAR(36) DEFAULT NULL,
  OWNER_ID          VARCHAR(255) NOT NULL,
  NOMINEE_ID        VARCHAR(255) NOT NULL,
  EVENT_TYPE        VARCHAR(32) NOT NULL,
  ACTOR_ID          VARCHAR(255) NOT NULL,
  DETAIL            TEXT DEFAULT NULL,
  OCCURRED_TIME     BIGINT NOT NULL,
  CHAIN_SEQUENCE    BIGINT NOT NULL,
  PREVIOUS_HASH     CHAR(64) NOT NULL,
  HASH              CHAR(64) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (EVENT_ID, ORG_ID),
  UNIQUE (CHAIN_SEQUENCE, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_nomination_event_nomination ON NOMINATION_EVENT (NOMINATION_ID);
CREATE INDEX IF NOT EXISTS idx_nomination_event_pair       ON NOMINATION_EVENT (OWNER_ID, NOMINEE_ID, OCCURRED_TIME);
CREATE INDEX IF NOT EXISTS idx_nomination_event_type       ON NOMINATION_EVENT (EVENT_TYPE);
CREATE INDEX IF NOT EXISTS idx_nomination_event_time       ON NOMINATION_EVENT (OCCURRED_TIME);

-- One acting session, or one refusal to start one. GRANTED_SCOPES records what
-- the impersonation token actually carried, which is the ceiling every action in
-- the session was bounded by.
CREATE TABLE IF NOT EXISTS NOMINEE_SESSION (
  SESSION_ID        CHAR(36) NOT NULL,
  NOMINATION_ID     CHAR(36) DEFAULT NULL,
  OWNER_ID          VARCHAR(255) NOT NULL,
  NOMINEE_ID        VARCHAR(255) NOT NULL,
  GRANTED_SCOPES    TEXT DEFAULT NULL,
  OUTCOME           VARCHAR(16) NOT NULL,
  DENIED_REASON     VARCHAR(255) DEFAULT NULL,
  STARTED_TIME      BIGINT NOT NULL,
  ENDED_TIME        BIGINT DEFAULT NULL,
  END_REASON        VARCHAR(32) DEFAULT NULL,
  CHAIN_SEQUENCE    BIGINT NOT NULL,
  PREVIOUS_HASH     CHAR(64) NOT NULL,
  HASH              CHAR(64) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (SESSION_ID, ORG_ID),
  UNIQUE (CHAIN_SEQUENCE, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_nominee_session_pair       ON NOMINEE_SESSION (OWNER_ID, NOMINEE_ID, STARTED_TIME);
CREATE INDEX IF NOT EXISTS idx_nominee_session_nomination ON NOMINEE_SESSION (NOMINATION_ID);
CREATE INDEX IF NOT EXISTS idx_nominee_session_outcome    ON NOMINEE_SESSION (OUTCOME);
CREATE INDEX IF NOT EXISTS idx_nominee_session_started    ON NOMINEE_SESSION (STARTED_TIME);

-- Every action attempted within a session, allowed or refused. This is the only
-- record of a nominee READING an owner's data, and the only record of a refusal:
-- neither ever reaches the Consent Server.
--
-- CHAIN_SEQUENCE restarts at zero for each session, so appends contend only
-- within one nominee's session rather than across the whole service.
CREATE TABLE IF NOT EXISTS NOMINEE_SESSION_EVENT (
  EVENT_ID          CHAR(36) NOT NULL,
  SESSION_ID        CHAR(36) NOT NULL,
  ACTION            VARCHAR(32) NOT NULL,
  RESOURCE_TYPE     VARCHAR(32) DEFAULT NULL,
  RESOURCE_ID       VARCHAR(255) DEFAULT NULL,
  DECISION          VARCHAR(16) NOT NULL,
  DENIED_REASON     VARCHAR(255) DEFAULT NULL,
  OCCURRED_TIME     BIGINT NOT NULL,
  CHAIN_SEQUENCE    BIGINT NOT NULL,
  PREVIOUS_HASH     CHAR(64) NOT NULL,
  HASH              CHAR(64) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (EVENT_ID, ORG_ID),
  UNIQUE (SESSION_ID, CHAIN_SEQUENCE, ORG_ID),
  CONSTRAINT FK_NOMINEE_SESSION_EVENT
    FOREIGN KEY (SESSION_ID, ORG_ID)
    REFERENCES NOMINEE_SESSION (SESSION_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_session_event_session  ON NOMINEE_SESSION_EVENT (SESSION_ID, OCCURRED_TIME);
CREATE INDEX IF NOT EXISTS idx_session_event_resource ON NOMINEE_SESSION_EVENT (RESOURCE_TYPE, RESOURCE_ID, OCCURRED_TIME);
CREATE INDEX IF NOT EXISTS idx_session_event_decision ON NOMINEE_SESSION_EVENT (DECISION);
CREATE INDEX IF NOT EXISTS idx_session_event_time     ON NOMINEE_SESSION_EVENT (OCCURRED_TIME);
